### ISSUE TITLE
NPE in SyncFrame.init during commit

### ISSUE THREAD

**Issue by interference-project** [interference-project/interference#10]
java.lang.NullPointerException
	at su.interference.core.SyncFrame.init(SyncFrame.java:90)
	at su.interference.core.SyncQueue.syncFramesFromQueue(SyncQueue.java:68)
	at su.interference.core.SyncQueue.run(SyncQueue.java:124)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuriy-glotanov** [comment]
fixed in 2020.2
