### ISSUE TITLE
lost IndexFrame.mv causes NPE 

### ISSUE THREAD

**Issue by yuriy-glotanov** [interference-project/interference#38]
During inserts in ResulSet index table periodically happens strange NPE caused by IndexFrame.mv is null:

NullPointerException
	at su.interference.core.ValueSet.compare(ValueSet.java:58)
	at su.interference.core.ValueSet.compareTo(ValueSet.java:49)
	at su.interference.core.IndexFrame.add(IndexFrame.java:161)
	at su.interference.persistent.Table.add(Table.java:1815)
	at su.interference.persistent.Table.persist(Table.java:1135)
	at su.interference.persistent.Table.persist(Table.java:1104)
	at su.interference.sql.ResultSetImpl.persist(ResultSetImpl.java:64)
	at su.interference.sql.SQLCursor.nextFrame2(SQLCursor.java:403)
	at su.interference.sql.SQLCursor.hasNextFrame(SQLCursor.java:433)
	at su.interference.sql.SQLCursor$2.run(SQLCursor.java:473)

**Comment by interference-project** [comment]
fixed in last hotfix patches
